#!/bin/bash
 # Lab 2 Expert
echo 'First task for file'
 touch shared.txt
 ls -la shared.txt
echo 'Second task for file'
 chmod 400 shared.txt
 ls -la shared.txt
echo 'First task for directory'
 touch shared
 ls -la shared
echo 'Second task for directory'
 chmod 400 shared
 ls -la shared
